// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: events_playlists_mapping.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const setPlaylistForEvent = `-- name: SetPlaylistForEvent :exec
INSERT INTO events_playlists_mapping (event_uuid, playlist_uuid) 
VALUES ($1, $2)
ON CONFLICT (event_uuid)
DO UPDATE SET playlist_uuid = $2
`

type SetPlaylistForEventParams struct {
	EventUuid    uuid.UUID `json:"event_uuid"`
	PlaylistUuid uuid.UUID `json:"playlist_uuid"`
}

func (q *Queries) SetPlaylistForEvent(ctx context.Context, arg SetPlaylistForEventParams) error {
	_, err := q.db.Exec(ctx, setPlaylistForEvent, arg.EventUuid, arg.PlaylistUuid)
	return err
}
