// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: events.sql

package database

import (
	"context"
)

const getAllEvents = `-- name: GetAllEvents :many
SELECT user_uuid, event_uuid, created_at, updated_at, event_code
FROM events
`

func (q *Queries) GetAllEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.UserUuid,
			&i.EventUuid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
