// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	UserUuid  pgtype.UUID        `json:"userUuid"`
	EventUuid pgtype.UUID        `json:"eventUuid"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	EventCode string             `json:"eventCode"`
}

type Playlist struct {
	EventUuid  pgtype.UUID        `json:"eventUuid"`
	PlaylistID string             `json:"playlistID"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

type Song struct {
	SongUri    string `json:"songUri"`
	PlaylistID string `json:"playlistID"`
	Count      int32  `json:"count"`
}

type User struct {
	ID           int64              `json:"id"`
	UserUuid     pgtype.UUID        `json:"userUuid"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	Username     string             `json:"username"`
	Email        interface{}        `json:"email"`
	PasswordHash []byte             `json:"passwordHash"`
	Activated    bool               `json:"activated"`
	Version      int32              `json:"version"`
}
